all: a.out
    g++ -O3 -I../irit/inc_irit main.cpp ../irit/circlink/circlink.o -L../irit/lib -lIritExt -lIritGrap -lIritUser -lIritRndr -lIritBool -lIritPrsr -lIritMdl -lIritMvar -lIritTrim -lIritTriv -lIritTrng -lIritSymb -lIritCagd -lIritGeom -lIritMisc -lIritXtra

